### ISSUE TITLE
Crash when Dynamite Module not available 

### ISSUE THREAD

**Issue by Sardorcode** [google-pay/compose-pay-button#16]
Hi, Thank you for library. I have crash reports in my app. How can I avoid crash when GMS not available.

PayButtonKt$PayButton$1$1.invoke
com.google.android.gms.dynamite.DynamiteModule$LoadingException - No acceptable module com.google.android.gms.wallet_dynamite found.

#StackTrace

Fatal Exception: java.lang.IllegalStateException: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module com.google.android.gms.wallet_dynamite found. Local version is 0 and remote version is 0.
       at com.google.android.gms.wallet.button.zzf.zzb(com.google.android.gms:play-services-wallet@@19.2.1:2)
       at com.google.android.gms.wallet.button.zzf.zza(com.google.android.gms:play-services-wallet@@19.2.1:1)
       at com.google.android.gms.wallet.button.PayButton.initialize(com.google.android.gms:play-services-wallet@@19.2.1:44)
       at com.google.pay.button.PayButtonKt$PayButton$1$1.invoke(PayButton.kt:58)
       at com.google.pay.button.PayButtonKt$PayButton$1$1.invoke(PayButton.kt:56)
       at androidx.compose.ui.viewinterop.ViewFactoryHolder.<init>(AndroidView.android.kt:337)
       at androidx.compose.ui.viewinterop.AndroidView_androidKt$createAndroidViewNodeFactory$1.invoke(AndroidView.android.kt:271)
       at androidx.compose.ui.viewinterop.AndroidView_androidKt$createAndroidViewNodeFactory$1.invoke(AndroidView.android.kt:270)
       at androidx.compose.ui.viewinterop.AndroidView_androidKt$AndroidView$$inlined$ComposeNode$1.invoke(Composables.kt:254)
       at androidx.compose.runtime.ComposerImpl$createNode$2.invoke(Composer.kt:1610)
       at androidx.compose.runtime.ComposerImpl$createNode$2.invoke(Composer.kt:1608)
       at androidx.compose.runtime.ComposerImpl$recordInsert$2.invoke(Composer.kt:3546)
       at androidx.compose.runtime.ComposerImpl$recordInsert$2.invoke(Composer.kt:3543)
       at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:818)
       at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:849)
       at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:625)
       at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:537)
       at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
       at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
       at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
       at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
       at android.view.Choreographer.doCallbacks(Choreographer.java:899)
       at android.view.Choreographer.doFrame(Choreographer.java:827)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7924)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by dmengelt** [comment]
@Sardorcode are you still able to re-produce this issue?

**Comment by dmengelt** [comment]
Closing for now. Please re-open if you still see the crash.
